### ISSUE TITLE
Missing Homepage should be an error

### ISSUE THREAD

**Issue by gildor478** [ocaml/oasis2opam#37]
Camelus now tags missing homepage as an error:
```
error 35: Missing field 'homepage'
````

oasis2opam should do the same at an earlier stage.

**Comment by Chris00** [comment]
On what package?

**Comment by gildor478** [comment]
https://github.com/ocaml/opam-repository/pull/9283

But I have fixed the missing field, so you can only see that camelus reported an error on commit 9c74eba

**Comment by Chris00** [comment]
Running `oasis2opam` on that package produces a bunch of warnings:
```
W: Consider adding "Description:" to your _oasis file
W: Consider adding "Maintainers:" to your _oasis file.
E: Give an email in oasis "Maintainers:" or "Authors:" fields (preferably the former).
W: Consider adding "Homepage:" to your _oasis file
I: No "SourceRepository" named "opam-pin", using "head".
W: Consider adding "BugReports:" to your _oasis file
I: OPAM directory "ocaml-fileutils.0.5.2" created.
```
You mean that you would like the opam package creation to fail—thus forbidding to fix the situation as you did—instead of just warning you—even if that means modifying your `_oasis` file (that [you have done](https://github.com/gildor478/ocaml-fileutils/blob/master/_oasis) except for the `Description` field) and uploading again your tarball?

**Comment by gildor478** [comment]
If I understand correctly, you think that I should:
1. upload the tarball of fileutils v1
2. generate the opam package 
3. let Camelus failed with a warning
4. fix fileutils/v1/opam until Camelus/other checks are green
5.  reflect my changes in _oasis

I agree that it is a valid approach. IMHO, it has some problems:
- the steps 3 and 4 are time and resources consuming, (11 checks done by the opam-repository ~1h latency). 
- people may not do 5 and will fail again the next time.

If you don't want to fail, an alternative approach is to have a "lint" subcommand that you can run before step 1, to ensure that an opam package can be generated. That should speed the whole process and move the optional step 5 to step 1.

**Comment by Chris00** [comment]
I transformed it—not yet pushed—into an "error" (in the sense of *oasis*) but the script still does not stop.  An alternative is, after step 2, to pay attention to the messages of  `oasis2opam`.  Maybe printing the errors in red would help with that?  Or we could fail by default and have a `--no-strict` (better name?) option?

**Comment by gildor478** [comment]
Maybe let's do the reverse and have a --strict to fail at first error.

I want to automate all of these checks to be able to have a ready to push source tarball that can be pushed to opam as well. Colorization is nice when you run the command line yourself, but in my case this will run in a jenkins builder without support for colors and I'll be very unlikely to check the output anyway.

**Comment by Chris00** [comment]
Let me know whether it is OK for you.
